//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int quoteid { get; set; }
        public string quotetype { get; set; }
        public string contact { get; set; }
        public string description { get; set; }
        public string duedate { get; set; }
        public string tasktype { get; set; }
    }
}
